#!/usr/bin/env bash
# Copyright 2026 zurichrich
# SPDX-License-Identifier: Apache-2.0
# Tests that the per-user config keeps one copy of the generated header across
# re-installs (ADT-354). adt-install.sh merges its core fields onto the existing
# config with yq, and that merge kept the head comment of both documents, so
# every install stacked one more copy of the header. Checks that a config which
# already has three copies ends with one, that a comment the user wrote at the
# top survives, that a second install changes nothing, and that a config with
# no head comment gets exactly one header.
# Runs offline, with --no-github and a stub gh.
set -uo pipefail

ADT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FAILS=0
pass() { printf '  \033[32mPASS\033[0m %s\n' "$1"; }
fail() { printf '  \033[31mFAIL\033[0m %s\n' "$1"; FAILS=$((FAILS+1)); }

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

PROJ="$TMP/proj"; mkdir -p "$PROJ"
git -C "$PROJ" init -q
git -C "$PROJ" config user.email t@t.t
git -C "$PROJ" config user.name t
git -C "$PROJ" commit -q --allow-empty -m init

BIN="$TMP/bin"; mkdir -p "$BIN"
cat > "$BIN/gh" <<'SH'
#!/usr/bin/env bash
case "$* " in
  *"auth status"*) echo "Token scopes: 'project'"; exit 0 ;;
  *"repo view"*"nameWithOwner"*) echo "me/proj"; exit 0 ;;
  *) exit 0 ;;
esac
SH
chmod +x "$BIN/gh"

USERP="$TMP/userp"; mkdir -p "$USERP"
CFG="$USERP/proj.yaml"
HEADER="generated by adt-install.sh"

run_install() {
  ( cd "$PROJ" && printf '\n\n\n\n\n\ny\n' | \
    PATH="$BIN:$PATH" HOME="$TMP/home" ADT_USER_PROJECTS="$USERP" \
    bash "$ADT_DIR/adt-install.sh" --no-github ) >"$TMP/install.log" 2>&1
}
headers() { grep -c "$HEADER" "$CFG"; }

seed_body() {
  cat <<EOF
name: proj
path: /stale/old/path
main_branch: main
remote: origin
claude_md: CLAUDE.md
cache_dir: /stale/cache
decision_log: docs/decisions.md
merger: me
github:
  repo: me/proj
  owner: me
kanban:
  id_prefix: TIX
EOF
}

echo "[test] a config holding three header copies ends with one"
{
  echo "# my own top comment"
  for _ in 1 2 3; do
    echo "# ADT project config — $HEADER. Lives outside the team repo so"
    echo "# your paths/secrets never enter git. Full schema: $ADT_DIR/projects/example.yaml"
  done
  seed_body
} > "$CFG"
[[ "$(headers)" == "3" ]] || fail "fixture did not seed three headers"
run_install || { fail "install exited non-zero"; tail -20 "$TMP/install.log"; }
[[ "$(headers)" == "1" ]] && pass "one header after install" || fail "$(headers) headers after install"
grep -q "^# my own top comment$" "$CFG" && pass "the user's top comment survives" \
  || fail "the user's top comment was removed"
[[ "$(yq -r '.kanban.id_prefix' "$CFG")" == "TIX" ]] && pass "config body intact" \
  || fail "config body damaged: id_prefix=$(yq -r '.kanban.id_prefix' "$CFG")"

echo "[test] a second install changes nothing"
before="$(shasum "$CFG" | cut -d' ' -f1)"
run_install || fail "second install exited non-zero"
[[ "$(headers)" == "1" ]] && pass "still one header" || fail "$(headers) headers after a re-run"
[[ "$(shasum "$CFG" | cut -d' ' -f1)" == "$before" ]] && pass "config unchanged by a re-run" \
  || fail "a re-run changed the config"

echo "[test] a config with no head comment gets exactly one header"
seed_body > "$CFG"
run_install || fail "install exited non-zero"
[[ "$(headers)" == "1" ]] && pass "one header added" || fail "$(headers) headers on a config that had none"

echo "[test] the user's repeated lines survive, and a header from another checkout is replaced"
{
  echo "# ---"
  echo "# deploy notes"
  echo "# ---"
  echo "# ADT project config — $HEADER. Lives outside the team repo so"
  echo "# your paths/secrets never enter git. Full schema: /some/other/checkout/projects/example.yaml"
  seed_body
} > "$CFG"
run_install || fail "install exited non-zero"
[[ "$(grep -c '^# ---$' "$CFG")" == "2" ]] && pass "both '# ---' lines kept" \
  || fail "the user's '# ---' lines: $(grep -c '^# ---$' "$CFG") left of 2"
[[ "$(grep -c 'Full schema:' "$CFG")" == "1" ]] && pass "one 'Full schema:' line" \
  || fail "$(grep -c 'Full schema:' "$CFG") 'Full schema:' lines"
grep -q "Full schema: $ADT_DIR/projects/example.yaml" "$CFG" && pass "it names this checkout" \
  || fail "the header still names the other checkout"

echo
[[ $FAILS -eq 0 ]] && { echo "test_install_config_header: PASS"; exit 0; } \
  || { echo "test_install_config_header: FAIL ($FAILS)"; exit 1; }
