#!/usr/bin/env python3
# Copyright 2026 zurichrich
# SPDX-License-Identifier: Apache-2.0
"""Score the dod-coverage-reviewer against the calibration cases (ADT-114 C1b).

Reads one `cases/<name>.verdict` per case (the reviewer's output block, saved
verbatim), compares it to `expected.json`, and writes
`docs/dod-coverage-calibration.md`.

Deliberately dumb: it does not judge the reviewer's prose, only whether the
verdict matched and whether a gapped case named the thing it was supposed to
catch. The point is a number a human can read at the merge-offer, not an
automated pass/fail — an LLM judge cannot be gated hermetically.

A POOR SCORE IS A LEGITIMATE RESULT. The correct response is to stop gating on
the judge (relax the --gate refusal to recording the review), never to re-run
until it looks good.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CASES = os.path.join(HERE, "cases")
# HERE is tools/calibration/dod-coverage → three levels up is the repo root.
ADT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
OUT = os.path.join(ADT_DIR, "docs", "dod-coverage-calibration.md")

VERDICT_RE = re.compile(r"^\*\*Verdict:\*\*\s*([A-Za-z-]+)", re.MULTILINE)


def read_verdict(path):
    """Return (verdict, full_text) or (None, '') when the case was not run."""
    if not os.path.isfile(path):
        return None, ""
    text = open(path, encoding="utf-8").read()
    m = VERDICT_RE.search(text)
    return (m.group(1).strip().upper() if m else ""), text


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=OUT, help="where to write the record")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the record instead of writing it")
    args = ap.parse_args(argv)

    expected = json.load(open(os.path.join(HERE, "expected.json"), encoding="utf-8"))
    rows, missing = [], []
    caught = gapped = fp = clean = 0

    for name in sorted(expected):
        spec = expected[name]
        verdict, text = read_verdict(os.path.join(CASES, name + ".verdict"))
        want = spec["expect"]
        is_gapped = want == "GAP"
        gapped += is_gapped
        clean += (not is_gapped)
        if verdict is None:
            missing.append(name)
            rows.append((name, want, "(not run)", "—", spec["gap_class"] or "—"))
            continue
        hit = verdict == want
        # A gapped case only counts as caught if it also NAMED the gap — a GAP
        # verdict pointing at the wrong thing is a lucky guess, not a catch.
        named = all(tok.lower() in text.lower() for tok in spec.get("must_mention", []))
        if is_gapped:
            caught += bool(hit and named)
            note = "caught" if (hit and named) else (
                "verdict right, gap not named" if hit else "MISSED")
        else:
            fp += (not hit)
            note = "ok" if hit else "FALSE POSITIVE"
        rows.append((name, want, verdict, note, spec["gap_class"] or "—"))

    lines = [
        "# dod-coverage-reviewer — calibration record",
        "",
        "Generated by `tools/calibration/dod-coverage/score.py`. See that",
        "directory's README for why this is a record a human reads rather than a",
        "test: an LLM judge cannot be graded hermetically, so the gate enforces",
        "that a review *happened* and this measures whether the reviewer is *worth*",
        "gating on.",
        "",
        "caught: %d/%d" % (caught, gapped),
        "",
        "- **caught** — gapped cases where the reviewer returned GAP *and* named",
        "  the gap. A GAP verdict pointing at the wrong thing is not a catch.",
        "- **false positives: %d/%d** — clean cases wrongly flagged. A judge that" % (fp, clean),
        "  flags everything is as useless as one that flags nothing.",
        "",
        "| case | expected | got | result | gap class |",
        "|---|---|---|---|---|",
    ]
    lines += ["| `%s` | %s | %s | %s | %s |" % r for r in rows]
    if missing:
        lines += ["", "> **Incomplete: %d case(s) not run** — %s. The score above is"
                       % (len(missing), ", ".join("`%s`" % m for m in missing)),
                  "> not a calibration until every case has a verdict."]
    lines += ["", "## What to do with this number", "",
              "A poor score is a legitimate result, not a failure of the exercise.",
              "The correct response is to stop gating on the judge — relax",
              "`adt_dod.py --gate` to recording the review without refusing — never",
              "to re-run the calibration until it looks good.", ""]
    body = "\n".join(lines)

    if args.dry_run:
        print(body)
        return 0
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(body)
    print("wrote %s — caught: %d/%d, false positives: %d/%d%s"
          % (args.out, caught, gapped, fp, clean,
             ", %d NOT RUN" % len(missing) if missing else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
